#!/usr/bin/env perl
use Mojolicious::Lite;
use JSON;
# Documentation browser under "/perldoc"
plugin 'PODRenderer';

plugin 'CHI'=>{
	default => {
		driver => 'Memory',
		global => 1
	}
};

sub enc{
	my $s = shift;
	$s = [] unless $s;
	return to_json($s);
}
sub dec{
	my $s = shift;
	return [] unless $s;
	return from_json($s);
}

get '/' => sub {
	my $self = shift;
	$self->render('index');
};

my $max = 100;
any '/#id/callback' => sub{
	my $self = shift;
	my $id = $self->param('id');
	my $msg = {};
	$msg->{action} = $self->param('action');
	$msg->{buddyId} = $self->param('buddyId');
	$msg->{groupId} = $self->param('groupId');
	$msg->{content} = $self->param('content');
	$msg->{time} = time();
	if( $msg->{action} ){
		my $arr = dec( $self->chi->get($id) );
		# 100개만 남기기
		my $len = @{$arr};
		if( $len > $max*1.5 ){
			$arr = [splice @{$arr},(-1*$max)];
		}
		push(@{$arr},$msg);
		$self->chi->set($id=>enc($arr));
		$self->render(text=>'ok');
	}
	else{
		$self->render(text=>'no action');
	}
};

get '/#id' => sub{
	my $self = shift;
	my $id = $self->param('id');
	my $data = $self->chi->get($id);
	$data = enc unless $data;
	$self->render(text=>$data);
};

get '/#id/flush' => sub{
	my $self = shift;
	my $id = $self->param('id');
	my $data = $self->chi->get($id);
	if( $data ){
		$self->chi->set($id=>enc);
	}
	else{
		$data = enc;
	}
	$self->render(text=>$data);
};

app->start;

__DATA__

@@ index.html.ep
% layout 'default';
% title '마이피플 봇 Callback Buffer';
<div class="page-header">
<h2><%= title %></h2>
</div>
<p>
<ol>
	<li>사용하려는 봇의 아이디를 <span class='label label-info'>mybot.bot</span>이라 했을 때,  </li>
	<li>콜백주소를 <%= url_for('')->to_abs %><span class='label label-info'>mybot.bot</span>/callback 으로 지정합니다.</li>
	<li><%= url_for('')->to_abs %><span class='label label-info'>mybot.bot</span> 에서 쌓인 메세지들을 <b>확인만</b> 할 수 있습니다.</li>
	<li><%= url_for('')->to_abs %><span class='label label-info'>mybot.bot</span>/flush 에서 쌓인 메세지들을 사용합니다. 조회 후 삭제됩니다. 봇에서는 이 주소를 이용해 쌓인 메세지들을 가져오도록 합니다.</li>
</ol>
</p>

@@ layouts/default.html.ep
<!DOCTYPE html>
<html>
  <head>
     <title><%= title %></title>
     <link rel="stylesheet" href="<%= url_for("/css/bootstrap.min.css") %>" />
     <script src="//ajax.googleapis.com/ajax/libs/jquery/1.9.1/jquery.min.js"></script>
     <script language="javascript" src="<%= url_for("/js/bootstrap.min.js") %>"></script>
  </head>
  <body>
    <div class="container">
       <%= content %>
    </div>
  </body>
</html>
